using System;

namespace Nybus.Configuration.QueueNameStrategies
{
    public class AutoGeneratedNameQueueNameStrategy : IQueueNameStrategy
    {
        private readonly string _prefix;
        public AutoGeneratedNameQueueNameStrategy() { }

        public AutoGeneratedNameQueueNameStrategy(string prefix)
        {
            if (prefix == null) throw new ArgumentNullException(nameof(prefix));
            _prefix = prefix;
        }

        public string GetQueueName()
        {
            if (string.IsNullOrEmpty(_prefix))
                return null;

            return $"{_prefix}-{Guid.NewGuid():N}";
        }
    }
}