using NUnit.Framework;
using Nybus.Configuration.QueueNameStrategies;
using Ploeh.AutoFixture;

namespace Tests.Configuration.QueueStrategies
{
    [TestFixture]
    public class AutoGeneratedNameQueueNameStrategyTests
    {
        private Fixture _fixture;

        [SetUp]
        public void Initialize()
        {
            _fixture = new Fixture();
        }

        [Test]
        public void GetQueueName_returns_null_if_no_prefix_is_used()
        {
            var sut = new AutoGeneratedNameQueueNameStrategy();

            var value = sut.GetQueueName();

            Assert.That(value, Is.Null);
        }

        [Test]
        public void GetQueueName_returns_prefixed_name_if_prefix_is_used()
        {
            string prefix = _fixture.Create<string>();

            var sut = new AutoGeneratedNameQueueNameStrategy(prefix);

            var value = sut.GetQueueName();

            Assert.That(value, Does.StartWith(prefix));
        }
    }
}